package com.adgyde.example;

import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.webkit.WebView;
import android.widget.Button;
import android.widget.Toast;

import androidx.appcompat.app.AppCompatActivity;

import com.adgyde.android.AdGyde;

public class MainActivity extends AppCompatActivity implements View.OnClickListener {

    private Button revenue, unique_Event, simple_event, counting_event,
            Computing_event, demography, user_id, loadWebPage, user_signin,getuserId;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
         setContentView(R.layout.activity_main);

        revenue = (Button) findViewById(R.id.revenue);
        revenue.setOnClickListener(this);

        unique_Event = (Button) findViewById(R.id.unique_Event);
        unique_Event.setOnClickListener(this);

        simple_event = (Button) findViewById(R.id.simple_event);
        simple_event.setOnClickListener(this);

        counting_event = (Button) findViewById(R.id.counting_event);
        counting_event.setOnClickListener(this);

        Computing_event = (Button) findViewById(R.id.Computing_event);
        Computing_event.setOnClickListener(this);

        demography = (Button) findViewById(R.id.demography);
        demography.setOnClickListener(this);

        user_id = (Button) findViewById(R.id.user_id);
        user_id.setOnClickListener(this);

        loadWebPage = (Button) findViewById(R.id.custom_userflow);
        loadWebPage.setOnClickListener(this);

        user_signin = (Button) findViewById(R.id.user_signin);
        user_signin.setOnClickListener(this);

        getuserId = (Button) findViewById(R.id.getuser_id);
        getuserId.setOnClickListener(this);
    }

    @Override
    public void onClick(View v) {
        switch (v.getId()) {
            case R.id.revenue:
                revenue();
                break;
            case R.id.unique_Event:
                Intent in1 = new Intent(this, UniqueEvent.class);
                startActivity(in1);
                break;
            case R.id.simple_event:
                simpleEvent();
                break;
            case R.id.counting_event:
                Intent in2 = new Intent(this, CountingEvent.class);
                startActivity(in2);
                break;
            case R.id.Computing_event:
                Intent in3 = new Intent(this, ComputingEvent.class);
                startActivity(in3);
                break;
            case R.id.demography:
                Intent in4 = new Intent(this, UserProfile.class);
                startActivity(in4);
                break;
            case R.id.user_id:
                setUserId();
                break;
            case R.id.getuser_id:
                getUserId();
                break;
            case R.id.custom_userflow:
                Intent in5 = new Intent(this, WebViewActivity.class);
                startActivity(in5);
            case R.id.user_signin:
                Intent in6 = new Intent(this, UserSignin.class);
                startActivity(in6);
        }


    }


 /* 
	 * Simple Event
	 * =============
     * The below code is the example to pass a simple event to the AdGyde SDK.
	 * This event requires only 1 Parameter which is the Event ID.
	 * 
	 * NOTE : Creating the Simple Event on Console with Event ID is Compulsory
	 *
	 */
    public void simpleEvent() {
        AdGyde.onSimpleEvent("SimpleEventID");
        Toast.makeText(this, "Simple event clicked", Toast.LENGTH_SHORT).show();
    }


  /* 
	 * Revenue Event
	 * =============
     * The below code is the example to pass a Revenue event to the AdGyde SDK.
	 * This event is useful to track revenue generated by the user in-app.
	 * Unit of the currency need not be passed, by default revenue is calculated in INR (Indian Rupees)
	 * 
	 * NOTE : There is no Need to create the Revenue Event on Console
	 *
	 */
    public void revenue() {
		// Revenue Event only requires the Revenue Value to be passed
        AdGyde.onRevenue(5);
        Toast.makeText(this, "Revenue clicked", Toast.LENGTH_SHORT).show();
    }

    /*
     * User_ID
     * =============
     * The below code is the example to pass a User_Id to the AdGyde SDK.
     *
     */

    public void setUserId(){
        AdGyde.setClientUserId("ADG1045984");
        Toast.makeText(this, "UserId = ADG1045984", Toast.LENGTH_SHORT).show();
    }


    public void getUserId(){
        String userid = AdGyde.getUserId();
        Toast.makeText(this, "Get UserId = " +userid, Toast.LENGTH_SHORT).show();

    }
}
